// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: playviewreq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PlayViewReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public long epId
    {
        get => __pbn__epId.GetValueOrDefault();
        set => __pbn__epId = value;
    }
    public bool ShouldSerializeepId() => __pbn__epId != null;
    public void ResetepId() => __pbn__epId = null;
    private long? __pbn__epId;

    [global::ProtoBuf.ProtoMember(2, Name = @"cid")]
    public long Cid
    {
        get => __pbn__Cid.GetValueOrDefault();
        set => __pbn__Cid = value;
    }
    public bool ShouldSerializeCid() => __pbn__Cid != null;
    public void ResetCid() => __pbn__Cid = null;
    private long? __pbn__Cid;

    [global::ProtoBuf.ProtoMember(3, Name = @"qn")]
    public long Qn
    {
        get => __pbn__Qn.GetValueOrDefault();
        set => __pbn__Qn = value;
    }
    public bool ShouldSerializeQn() => __pbn__Qn != null;
    public void ResetQn() => __pbn__Qn = null;
    private long? __pbn__Qn;

    [global::ProtoBuf.ProtoMember(4, Name = @"fnver")]
    public int Fnver
    {
        get => __pbn__Fnver.GetValueOrDefault();
        set => __pbn__Fnver = value;
    }
    public bool ShouldSerializeFnver() => __pbn__Fnver != null;
    public void ResetFnver() => __pbn__Fnver = null;
    private int? __pbn__Fnver;

    [global::ProtoBuf.ProtoMember(5, Name = @"fnval")]
    public int Fnval
    {
        get => __pbn__Fnval.GetValueOrDefault();
        set => __pbn__Fnval = value;
    }
    public bool ShouldSerializeFnval() => __pbn__Fnval != null;
    public void ResetFnval() => __pbn__Fnval = null;
    private int? __pbn__Fnval;

    [global::ProtoBuf.ProtoMember(6, Name = @"download")]
    public uint Download
    {
        get => __pbn__Download.GetValueOrDefault();
        set => __pbn__Download = value;
    }
    public bool ShouldSerializeDownload() => __pbn__Download != null;
    public void ResetDownload() => __pbn__Download = null;
    private uint? __pbn__Download;

    [global::ProtoBuf.ProtoMember(7)]
    public int forceHost
    {
        get => __pbn__forceHost.GetValueOrDefault();
        set => __pbn__forceHost = value;
    }
    public bool ShouldSerializeforceHost() => __pbn__forceHost != null;
    public void ResetforceHost() => __pbn__forceHost = null;
    private int? __pbn__forceHost;

    [global::ProtoBuf.ProtoMember(8, Name = @"fourk")]
    public bool Fourk
    {
        get => __pbn__Fourk.GetValueOrDefault();
        set => __pbn__Fourk = value;
    }
    public bool ShouldSerializeFourk() => __pbn__Fourk != null;
    public void ResetFourk() => __pbn__Fourk = null;
    private bool? __pbn__Fourk;

    [global::ProtoBuf.ProtoMember(9, Name = @"spmid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Spmid
    {
        get => __pbn__Spmid ?? "";
        set => __pbn__Spmid = value;
    }
    public bool ShouldSerializeSpmid() => __pbn__Spmid != null;
    public void ResetSpmid() => __pbn__Spmid = null;
    private string __pbn__Spmid;

    [global::ProtoBuf.ProtoMember(10)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fromSpmid
    {
        get => __pbn__fromSpmid ?? "";
        set => __pbn__fromSpmid = value;
    }
    public bool ShouldSerializefromSpmid() => __pbn__fromSpmid != null;
    public void ResetfromSpmid() => __pbn__fromSpmid = null;
    private string __pbn__fromSpmid;

    [global::ProtoBuf.ProtoMember(11)]
    public int teenagersMode
    {
        get => __pbn__teenagersMode.GetValueOrDefault();
        set => __pbn__teenagersMode = value;
    }
    public bool ShouldSerializeteenagersMode() => __pbn__teenagersMode != null;
    public void ResetteenagersMode() => __pbn__teenagersMode = null;
    private int? __pbn__teenagersMode;

    [global::ProtoBuf.ProtoMember(12)]
    [global::System.ComponentModel.DefaultValue(CodeType.Nocode)]
    public CodeType preferCodecType
    {
        get => __pbn__preferCodecType ?? CodeType.Nocode;
        set => __pbn__preferCodecType = value;
    }
    public bool ShouldSerializepreferCodecType() => __pbn__preferCodecType != null;
    public void ResetpreferCodecType() => __pbn__preferCodecType = null;
    private CodeType? __pbn__preferCodecType;

    [global::ProtoBuf.ProtoMember(13)]
    public bool isPreview
    {
        get => __pbn__isPreview.GetValueOrDefault();
        set => __pbn__isPreview = value;
    }
    public bool ShouldSerializeisPreview() => __pbn__isPreview != null;
    public void ResetisPreview() => __pbn__isPreview = null;
    private bool? __pbn__isPreview;

    [global::ProtoBuf.ProtoMember(14)]
    public long roomId
    {
        get => __pbn__roomId.GetValueOrDefault();
        set => __pbn__roomId = value;
    }
    public bool ShouldSerializeroomId() => __pbn__roomId != null;
    public void ResetroomId() => __pbn__roomId = null;
    private long? __pbn__roomId;

    [global::ProtoBuf.ProtoContract()]
    public enum CodeType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NOCODE")]
        Nocode = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CODE264")]
        Code264 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CODE265")]
        Code265 = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
