// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: network.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Network : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue(Type.NtUnknown)]
    public Type type
    {
        get => __pbn__type ?? Type.NtUnknown;
        set => __pbn__type = value;
    }
    public bool ShouldSerializetype() => __pbn__type != null;
    public void Resettype() => __pbn__type = null;
    private Type? __pbn__type;

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue(Tf.TfUnknown)]
    public Tf tf
    {
        get => __pbn__tf ?? Tf.TfUnknown;
        set => __pbn__tf = value;
    }
    public bool ShouldSerializetf() => __pbn__tf != null;
    public void Resettf() => __pbn__tf = null;
    private Tf? __pbn__tf;

    [global::ProtoBuf.ProtoMember(3, Name = @"oid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Oid
    {
        get => __pbn__Oid ?? "";
        set => __pbn__Oid = value;
    }
    public bool ShouldSerializeOid() => __pbn__Oid != null;
    public void ResetOid() => __pbn__Oid = null;
    private string __pbn__Oid;

    [global::ProtoBuf.ProtoContract(Name = @"TYPE")]
    public enum Type
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NT_UNKNOWN")]
        NtUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WIFI")]
        Wifi = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CELLULAR")]
        Cellular = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"OFFLINE")]
        Offline = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"OTHERNET")]
        Othernet = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ETHERNET")]
        Ethernet = 5,
    }

    [global::ProtoBuf.ProtoContract(Name = @"TF")]
    public enum Tf
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TF_UNKNOWN")]
        TfUnknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"U_CARD")]
        UCard = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"U_PKG")]
        UPkg = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"C_CARD")]
        CCard = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"C_PKG")]
        CPkg = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"T_CARD")]
        TCard = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"T_PKG")]
        TPkg = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
