// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: dmviewreq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class DmViewReq : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
    public long Pid
    {
        get => __pbn__Pid.GetValueOrDefault();
        set => __pbn__Pid = value;
    }
    public bool ShouldSerializePid() => __pbn__Pid != null;
    public void ResetPid() => __pbn__Pid = null;
    private long? __pbn__Pid;

    [global::ProtoBuf.ProtoMember(2, Name = @"oid")]
    public long Oid
    {
        get => __pbn__Oid.GetValueOrDefault();
        set => __pbn__Oid = value;
    }
    public bool ShouldSerializeOid() => __pbn__Oid != null;
    public void ResetOid() => __pbn__Oid = null;
    private long? __pbn__Oid;

    [global::ProtoBuf.ProtoMember(3, Name = @"type")]
    public int Type
    {
        get => __pbn__Type.GetValueOrDefault();
        set => __pbn__Type = value;
    }
    public bool ShouldSerializeType() => __pbn__Type != null;
    public void ResetType() => __pbn__Type = null;
    private int? __pbn__Type;

    [global::ProtoBuf.ProtoMember(4, Name = @"spmid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Spmid
    {
        get => __pbn__Spmid ?? "";
        set => __pbn__Spmid = value;
    }
    public bool ShouldSerializeSpmid() => __pbn__Spmid != null;
    public void ResetSpmid() => __pbn__Spmid = null;
    private string __pbn__Spmid;

    [global::ProtoBuf.ProtoMember(5)]
    public int isHardBoot
    {
        get => __pbn__isHardBoot.GetValueOrDefault();
        set => __pbn__isHardBoot = value;
    }
    public bool ShouldSerializeisHardBoot() => __pbn__isHardBoot != null;
    public void ResetisHardBoot() => __pbn__isHardBoot = null;
    private int? __pbn__isHardBoot;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
