// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: locale.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Locale : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    public LocaleIds cLocale { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public LocaleIds sLocale { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class LocaleIds : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language
        {
            get => __pbn__Language ?? "";
            set => __pbn__Language = value;
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private string __pbn__Language;

        [global::ProtoBuf.ProtoMember(2, Name = @"script")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Script
        {
            get => __pbn__Script ?? "";
            set => __pbn__Script = value;
        }
        public bool ShouldSerializeScript() => __pbn__Script != null;
        public void ResetScript() => __pbn__Script = null;
        private string __pbn__Script;

        [global::ProtoBuf.ProtoMember(3, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region
        {
            get => __pbn__Region ?? "";
            set => __pbn__Region = value;
        }
        public bool ShouldSerializeRegion() => __pbn__Region != null;
        public void ResetRegion() => __pbn__Region = null;
        private string __pbn__Region;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
