// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: metadata.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Metadata : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accessKey
    {
        get => __pbn__accessKey ?? "";
        set => __pbn__accessKey = value;
    }
    public bool ShouldSerializeaccessKey() => __pbn__accessKey != null;
    public void ResetaccessKey() => __pbn__accessKey = null;
    private string __pbn__accessKey;

    [global::ProtoBuf.ProtoMember(2)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobiApp
    {
        get => __pbn__mobiApp ?? "";
        set => __pbn__mobiApp = value;
    }
    public bool ShouldSerializemobiApp() => __pbn__mobiApp != null;
    public void ResetmobiApp() => __pbn__mobiApp = null;
    private string __pbn__mobiApp;

    [global::ProtoBuf.ProtoMember(3, Name = @"device")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Device
    {
        get => __pbn__Device ?? "";
        set => __pbn__Device = value;
    }
    public bool ShouldSerializeDevice() => __pbn__Device != null;
    public void ResetDevice() => __pbn__Device = null;
    private string __pbn__Device;

    [global::ProtoBuf.ProtoMember(4, Name = @"build")]
    public int Build
    {
        get => __pbn__Build.GetValueOrDefault();
        set => __pbn__Build = value;
    }
    public bool ShouldSerializeBuild() => __pbn__Build != null;
    public void ResetBuild() => __pbn__Build = null;
    private int? __pbn__Build;

    [global::ProtoBuf.ProtoMember(5, Name = @"channel")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Channel
    {
        get => __pbn__Channel ?? "";
        set => __pbn__Channel = value;
    }
    public bool ShouldSerializeChannel() => __pbn__Channel != null;
    public void ResetChannel() => __pbn__Channel = null;
    private string __pbn__Channel;

    [global::ProtoBuf.ProtoMember(6, Name = @"buvid")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Buvid
    {
        get => __pbn__Buvid ?? "";
        set => __pbn__Buvid = value;
    }
    public bool ShouldSerializeBuvid() => __pbn__Buvid != null;
    public void ResetBuvid() => __pbn__Buvid = null;
    private string __pbn__Buvid;

    [global::ProtoBuf.ProtoMember(7, Name = @"platform")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Platform
    {
        get => __pbn__Platform ?? "";
        set => __pbn__Platform = value;
    }
    public bool ShouldSerializePlatform() => __pbn__Platform != null;
    public void ResetPlatform() => __pbn__Platform = null;
    private string __pbn__Platform;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
